language: scala
scala:
  - 2.11.4
sudo: true
dist: precise

dist: trusty

jdk:
  - oraclejdk8
  - openjdk8

script: travis_wait 30 mvn clean test -PscalaBaseVersion=2.11.4
after_success:
  - bash <(curl -s https://codecov.io/bash)
